### ISSUE TITLE
password protected website undocumented

### ISSUE THREAD

**Issue by ph1l** [SignalK/signalk-java#10]
The passord for Configuration and Administration options available via the web interface are undocumented, afaict.

What is the default, and how can we change it?

**Comment by rob42** [comment]
Its on the Readme page :-)
user admin, password s3cr3t. Its hard coded for now, will be configureable later.

**Comment by ph1l** [comment]
ah.. I grepped for password, passwd and pass and didn't see it :-)

Thanks!

**Comment by rob42** [comment]
Now set in the config, same defaults
