### ISSUE TITLE
unreachable after a few days

### ISSUE THREAD

**Issue by ph1l** [SignalK/signalk-java#13]
Since using the signalk-java based raspberrypi server, I've noticed that the server goes offline after a few days. two weeks in a row.
```
elektron@yoga:~$ ssh pi@raspberrypi.boat
Connection closed by 10.0.2.197 port 22
```

I don't have any logs yet, but will update this issue when I can make it out to the boat.

Anyone else noticed similar behavior?

**Comment by rob42** [comment]
Ive not seen this myself, but I usually only run the RPi for 24-48 hrs. This kind of behaviour can be caused by many things, incl power supply interruptions, disk full, or memory leaks. 

Ive checked carefully for memory-leaks etc in the past but not recently. I will run my test server  on my desk and see if I can reproduce this.

**Comment by ph1l** [comment]
Sorry, I think this was a hardware issue:

```
[Mon Apr 17 06:19:32 2017] bcm2835-dma 3f007000.dma: DMA transfer could not be terminated
[Mon Apr 17 06:19:32 2017] mmcblk0: error -110 transferring data, sector 30339456, nr 256, cmd response 0x900, card status 0xb00
[Mon Apr 17 06:19:34 2017] mmc0: card never left busy state
[Mon Apr 17 06:19:34 2017] mmc0: tried to reset card
[Mon Apr 17 06:19:34 2017] mmcblk0: retrying using single block read
[Mon Apr 17 06:19:34 2017] mmcblk0: error -110 sending status command, retrying
[Mon Apr 17 06:19:34 2017] mmcblk0: error -110 sending status command, retrying
[Mon Apr 17 06:19:34 2017] mmcblk0: error -110 sending status command, aborting
[Mon Apr 17 06:19:34 2017] EXT4-fs warning (device mmcblk0p2): ext4_end_bio:329: I/O error -5 writing to inode 262634 (offset 0 size 0 starting block 302339)
```
