### ISSUE TITLE
raspian setup script

### ISSUE THREAD

**Issue by ph1l** [SignalK/signalk-java#2]
got a specific bug report about the setup script?

    //there is a script that sets up your wifi, dns, and server auto-start.
    //its a bit troublesome at present, so YMMV

**Comment by rob42** [comment]
Depends on a lot of variables, RPi2/3, raspbain wheezy/jessie, WIFI chip, etc.
Leaving this open - please add specifics if anyone finds any. Then we can improve the script. We will need as much detail as you can manage, at least RPi details, OS details, and any other hardware, plus screen output and your sequence of actions before the error.

**Comment by rob42** [comment]
Closing as very old and many changes now
