### ISSUE TITLE
README.md contains some errors

### ISSUE THREAD

**Issue by lburaggi** [SignalK/signalk-java#22]
The file README.md contains the following errors:

1. the line showing the command `source <(curl -s https://raw.githubusercontent.com/SignalK/signalk-java/jdk11/setup_raspbian.sh)` points to the `signalk-java/jdk11/setup_raspbian.sh` script while the link in the line just below shows a detailed Install Procedure where the setup_raspbian_sh is taken from a different GIT branch: `source <(curl -s https://raw.githubusercontent.com/SignalK/signalk-java/master/setup_raspbian.sh)`
1. the link in line `Goto INSTALL.md (https://github.com/SignalK/signalk-java/blob/artemis/INSTALL.md)` is broken

**Comment by rob42** [comment]
Thanks, fixed
Trying to keep the master and jdk11 branches in sync is a hassle for these files. I have to be careful when I merge them as the urls etc are different, but the rest is the same...
