### ISSUE TITLE
Script setup_raspbian.sh stops with a bash error

### ISSUE THREAD

**Issue by lburaggi** [SignalK/signalk-java#23]
**Issue Description**
When running the script pointed to by the README.md file: `source <(curl -s https://raw.githubusercontent.com/SignalK/signalk-java/jdk11/setup_raspbian.sh)
` (note the `jdk11` folder) the following bash errors are generated:
1. `Bash: $1 unbound variable`, apparently due to the `dev=$1` assignment
1. In line 281 the command `sudo ntpd -gq` , generates an error if the ntp service is already running (this happens if the script is restarted after a failure). I suggest to insert a `sudo systemctl stop ntp` just before line 281
1. In line 314 the command `sudo cp /lib/udev/hwclock-set.orig /lib/udev/hwclock-set` stops the script because the file .orig doesn't exist. It is created in the "then" part of the if, and it cannot exist if the "else" part is executed. I suggest to delete the line 314.

**To Reproduce**
1. simply follow the README.md instructions and reply "N" to the "hardware (RTC) clock module", correcting each error and executing the script again

**Environment :**
 - Device: Rpi3+
 - OS: fresh installed Raspbian (2018-11-13-raspbian-stretch-lite.zip)

**Comment by lburaggi** [comment]
Please note that the error happens when you reply "N" to the "Do you have a hardware (RTC) clock module?"

**Comment by rob42** [comment]
Thanks. This is only happening in the jdk11 branch, which was wrongly pointed to by #22 for master (now fixed).
I'm currently adding some functionality to the jdk11 branch to handle rtc clocks and correct dates etc, looks like I pushed too soon.
Fixed now.
